sudo: required
dist: trusty

install:
  - sudo apt-get -qy install libqt5webkit5-dev qttools5-dev qtscript5-dev 
  - sudo apt-get -qy install libdbusmenu-qt-dev libdbusmenu-qt5-dev
  - sudo apt-get -qy install libphonon-dev libphonon4qt5-dev
  - sudo apt-get -qy install libqca2-dev
  - sudo apt-get -qy install qt4-dev-tools qttools5-dev-tools
  - sudo apt-get -qy install libphonon4qt5experimental4 # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805096

language: cpp
cache: ccache

compiler:
  - gcc
  - clang

env:
  - QT_VERSION=qt4
  - QT_VERSION=qt5

script:
  - mkdir build
  - cd build
  - if [ "$QT_VERSION" = "qt4" ]; then cmake ..; fi
  - if [ "$QT_VERSION" = "qt5" ]; then cmake -DUSE_QT5=ON ..; fi
  - make

matrix:
  exclude:
    - compiler: clang
      env: QT_VERSION=qt4
